version: '3.8'

services:
    backend:
        build:
            context: ./docker/backend
        volumes:
            - ./backend:/var/www/html

    web:
        image: nginx:latest
        ports:
            - 80:80
            - 9000:9000
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - backend

    db:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: poop
