version: '3.8'

services:
    backend:
        build:
            context: ./docker/backend
        volumes:
            - ./backend:/var/www/html

    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 9000:9000
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - backend

    mysql:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:rw
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: poop
